version: 2
jobs:
  build:
    working_directory: ~/repo/01-Authenticate-RS256
    machine: true
           
    steps:
      - checkout:
         path: ~/repo

      - run: 
          name: Set .env file
          command: |
              mv .env.example .env
              sed -i "s/{DOMAIN}/$AUTH0_TEST_DOMAIN/g" .env
              sed -i "s/{AUTH0_AUDIENCE}/$AUTH0_TEST_AUDIENCE/g" .env    
              head .env
 
      - run: 
           name: background server
           command: sh exec.sh
           background: true
           
      - run:
           name: Wait until server is online
           command: |
              until $(curl --output /dev/null --silent --head --fail http://localhost:3010/api/public); do
                  sleep 5
              done
         
      - run:
          name: Clone script test
          command: git clone https://github.com/auth0-samples/api-quickstarts-tests test
          
      - run: 
          name: Prepare environment variables for test
          command: |
            cd test
            echo "AUTH0_DOMAIN=$AUTH0_TEST_DOMAIN" >> .env
            echo "API_IDENTIFIER=$AUTH0_TEST_AUDIENCE" >> .env
            echo "AUTH0_CLIENT_ID_1=$AUTH0_TEST_CLIENT_ID1" >> .env
            echo "AUTH0_CLIENT_SECRET_1=$AUTH0_TEST_CLIENT_SECRET1" >> .env
            echo "AUTH0_CLIENT_ID_2=$AUTH0_TEST_CLIENT_ID2" >> .env
            echo "AUTH0_CLIENT_SECRET_2=$AUTH0_TEST_CLIENT_SECRET2" >> .env
            echo "AUTH0_CLIENT_ID_3=$AUTH0_TEST_CLIENT_ID3" >> .env
            echo "AUTH0_CLIENT_SECRET_3=$AUTH0_TEST_CLIENT_SECRET3" >> .env
            echo "AUTH0_CLIENT_ID_4=$AUTH0_TEST_CLIENT_ID4" >> .env
            echo "AUTH0_CLIENT_SECRET_4=$AUTH0_TEST_CLIENT_SECRET4" >> .env
            echo "API_URL=http://localhost:3010" >> .env

      - run:
          name: Install test script dependency
          command: cd test && npm install 

      - run:
          name: Test
          command: cd test && npm test
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Quickstart API Tests

# Common Logic
defaults: &defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Prepare environment variables
          command: | 
            cd $AUTH0_CFG
            mv .env.example .env
            sed -i 's|{DOMAIN}|'$auth0_domain'|g' .env            
            if [[ $AUTH0_CFG = *"RS256"* ]];
            then
                sed -i 's|{API_IDENTIFIER}|'$api_identifier'|g' .env
            else
                sed -i 's|{API_IDENTIFIER}|'$api_identifier_hs256'|g' .env
                sed -i 's|{API_SIGNING_SECRET}|'$api_signing_secret'|g' .env
            fi
      - run:
          name: Background Server
          command: cd $AUTH0_CFG && sh exec.sh
          background: true
      - run:
          name: Wait until server is online 
          command: |
            until $(curl --silent --head --output /dev/null --fail http://localhost:3010/api/public); do
                sleep 5
            done
      - run:
          name: Prepare tests
          command: |
            cd test
            echo "AUTH0_DOMAIN=$auth0_domain" >> .env
            if [[ $AUTH0_CFG = *"RS256"* ]];
            then
                echo "API_IDENTIFIER=$api_identifier" >> .env
            else
                echo "API_IDENTIFIER=$api_identifier_hs256" >> .env
            fi
            echo "AUTH0_CLIENT_ID_1=$client_id_scopes_none" >> .env
            echo "AUTH0_CLIENT_SECRET_1=$client_secret_scopes_none" >> .env
            echo "AUTH0_CLIENT_ID_2=$client_id_scopes_read" >> .env
            echo "AUTH0_CLIENT_SECRET_2=$client_secret_scopes_read" >> .env
            echo "AUTH0_CLIENT_ID_3=$client_id_scopes_write" >> .env
            echo "AUTH0_CLIENT_SECRET_3=$client_secret_scopes_write" >> .env
            echo "AUTH0_CLIENT_ID_4=$client_id_scopes_readwrite" >> .env
            echo "AUTH0_CLIENT_SECRET_4=$client_secret_scopes_readwrite" >> .env
            echo "API_URL=http://localhost:3010" >> .env
            npm install
      - run:
          name: Execute automated tests
          command: cd test && npm test       
# Jobs and Workflows
version: 2
jobs: 
  checkout:
    machine: true
    steps:
      - checkout
      - run:
          name: Clone test script
          command: git clone https://github.com/auth0-samples/api-quickstarts-tests test
      - persist_to_workspace:
          root: ~/ 
          paths:
            - project
            - test
  01-Authenticate-RS256:
    machine: true
    environment:
      - AUTH0_CFG: 01-Authenticate-RS256
      - SAMPLE_PATH: 01-Authenticate-RS256
    <<: *defaults
  02-Authenticate-HS256:
    machine: true
    environment:
      - AUTH0_CFG: 02-Authenticate-HS256
      - SAMPLE_PATH: 02-Authenticate-HS256
    <<: *defaults
workflows:
  version: 2
  API-Tests:
    jobs:
      - checkout:
          context: Quickstart API Tests
      - 01-Authenticate-RS256:
          context: Quickstart API Tests
          requires:
            - checkout
      - 02-Authenticate-HS256:
          context: Quickstart API Tests
          requires:
            - checkout